name: Run Commands on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Run commands on EC2 instance
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Running commands on EC2 instance..."
          cd fleetbase
          # Example command: pull latest code
          git pull origin main
          # Example command: install dependencies
          docker-compose up --build -d
          # Example command: restart service
          docker exec -i fleetbase-application-1 sh deploy.sh
